"""
Export dota_stats.db to docs/data.js for the static dashboard.

Exports MATCHES ONLY — standings and hero records are aggregated in the
browser. That is deliberate: the year filter has to recompute every
average and win rate from scratch, so shipping pre-aggregated totals
would mean shipping one set per year and keeping them in sync.

Written as a JS assignment rather than .json so the page works from
file:// as well as GitHub Pages — no fetch, no CORS, no local server.

    python export_web.py
"""

import json
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).parent
DB = ROOT / "dota_stats.db"
OUT = ROOT / "docs" / "data.js"


def rows(cur, sql, args=()):
    cur.execute(sql, args)
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, r)) for r in cur.fetchall()]


def main() -> int:
    if not DB.exists():
        sys.exit("dota_stats.db not found -- run `python load.py` first.")
    con = sqlite3.connect(DB)
    cur = con.cursor()

    # Match ids are globally sequential, so they are the authoritative
    # chronology. The one match with no id sorts last.
    matches = rows(cur, """
        SELECT id, dota_match_id, played_on, played_at, duration_seconds,
               game_mode, radiant_team_name, dire_team_name,
               radiant_score, dire_score, winning_side, result_confidence, notes
        FROM matches
        ORDER BY COALESCE(CAST(dota_match_id AS INTEGER), 9999999999)
    """)

    parts = rows(cur, """
        SELECT mp.match_id, vp.player_name AS name, mp.side, mp.hero,
               mp.hero_level AS lvl, mp.kills AS k, mp.deaths AS d,
               mp.assists AS a, mp.net_worth AS net, mp.last_hits AS lh,
               mp.denies AS dn, mp.gpm, mp.xpm, mp.hero_damage AS hdmg,
               mp.building_damage AS bdmg, mp.healing AS heal,
               CASE WHEN mp.side = m.winning_side THEN 1 ELSE 0 END AS won
        FROM match_players mp
        JOIN matches m ON m.id = mp.match_id
        JOIN v_player vp ON vp.raw_id = mp.player_id
    """)

    by_match = {}
    for p in parts:
        by_match.setdefault(p.pop("match_id"), []).append(p)

    def strip_side(r):
        return {k: v for k, v in r.items() if k != "side"}

    for i, m in enumerate(matches):
        roster = sorted(by_match.get(m["id"], []), key=lambda r: -(r["net"] or 0))
        m["radiant"] = [strip_side(r) for r in roster if r["side"] == "radiant"]
        m["dire"]    = [strip_side(r) for r in roster if r["side"] == "dire"]
        m["seq"] = i + 1
        m["year"] = (m["played_on"] or "")[:4]
        m.pop("id", None)

    aliases = rows(cur, """
        SELECT p.display_name AS alias, c.display_name AS canonical
        FROM players p JOIN players c ON c.id = p.merged_into
    """)

    years = sorted({m["year"] for m in matches if m["year"]}, reverse=True)

    payload = {
        "meta": {
            "years": years,
            "aliases": aliases,
            "generated": None,   # stamped by the caller if ever needed
        },
        "matches": matches,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/* Generated by export_web.py -- do not edit by hand. */\n"
        "window.LOBBY = " + json.dumps(payload, ensure_ascii=False,
                                       separators=(",", ":")) + ";\n",
        encoding="utf-8")

    kb = OUT.stat().st_size / 1024
    print(f"  wrote {OUT.relative_to(ROOT)}  ({kb:.1f} KB)")
    print(f"  {len(matches)} matches | years: {', '.join(years)} | "
          f"{len(parts)} player-games | {len(aliases)} merges")

    sync_hero_slugs(cur)
    stamp_assets()
    return 0


# Display name -> Valve's internal hero name, where the two differ.
HERO_SPECIAL = {
    "Anti-Mage": "antimage", "Centaur Warrunner": "centaur",
    "Clockwerk": "rattletrap", "Doom": "doom_bringer", "Io": "wisp",
    "Lifestealer": "life_stealer", "Magnus": "magnataur",
    "Nature's Prophet": "furion", "Necrophos": "necrolyte",
    "Outworld Destroyer": "obsidian_destroyer", "Queen of Pain": "queenofpain",
    "Shadow Fiend": "nevermore", "Timbersaw": "shredder",
    "Treant Protector": "treant", "Underlord": "abyssal_underlord",
    "Vengeful Spirit": "vengefulspirit", "Windranger": "windrunner",
    "Wraith King": "skeleton_king", "Zeus": "zuus",
}
CDN = "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes"


def sync_hero_slugs(cur) -> None:
    """
    Keep docs/heroes.js covering every hero in the database.

    Only heroes NOT already mapped are looked up, so this stays fast and
    works offline once the map is warm. A hero with no entry simply renders
    without art -- it must never break the page or block a deploy.
    """
    import json as _json
    import re
    import urllib.request

    out = ROOT / "docs" / "heroes.js"
    have = {}
    if out.exists():
        m = re.search(r"window\.HERO_SLUG\s*=\s*(\{.*?\});", out.read_text(encoding="utf-8"), re.S)
        if m:
            have = _json.loads(m.group(1))

    heroes = [r[0] for r in cur.execute(
        "SELECT DISTINCT hero FROM match_players WHERE hero IS NOT NULL")]
    missing = [h for h in heroes if h not in have]
    if not missing:
        print(f"  hero art: {len(have)} mapped, none new")
        return

    added, failed = 0, []
    for h in missing:
        slug = HERO_SPECIAL.get(h) or re.sub(r"[^a-z0-9]+", "_", h.lower()).strip("_")
        try:
            req = urllib.request.Request(f"{CDN}/{slug}.png", method="HEAD",
                                         headers={"User-Agent": "Mozilla/5.0"})
            ok = urllib.request.urlopen(req, timeout=15).status == 200
        except Exception:
            ok = False
        if ok:
            have[h] = slug
            added += 1
        else:
            failed.append((h, slug))

    out.write_text(
        "/* Display name -> Valve internal hero slug. Every entry HEAD-verified\n"
        "   against the Dota 2 CDN. Regenerated by export_web.py. */\n"
        "window.HERO_SLUG = " + _json.dumps(have, ensure_ascii=False, indent=0,
                                            sort_keys=True) + ";\n",
        encoding="utf-8")
    print(f"  hero art: {len(have)} mapped (+{added} new)")
    for h, s in failed:
        print(f"    ! no image for {h!r} (tried {s!r}) -- it will render without art")


def stamp_assets() -> None:
    """
    Rewrite index.html's asset links as `app.js?v=<hash>`.

    Without this, a returning visitor can end up holding a CACHED copy of
    one file and a fresh copy of another -- e.g. the previous app.js with
    the current data.js. The two disagree about the shape of the data and
    the page renders blank, which is exactly what happened on the first
    redesign deploy. Hashing the content means any change to any asset
    produces new URLs, so the browser can never mix versions.
    """
    import hashlib
    import re

    docs = ROOT / "docs"
    assets = ["style.css", "app.js", "data.js", "heroes.js"]
    h = hashlib.sha1()
    for a in assets:
        p = docs / a
        if p.exists():
            h.update(p.read_bytes())
    ver = h.hexdigest()[:8]

    idx = docs / "index.html"
    html = idx.read_text(encoding="utf-8")
    before = html
    for a in assets:
        html = re.sub(r'(href|src)="' + re.escape(a) + r'(\?v=[0-9a-f]+)?"',
                      lambda m: f'{m.group(1)}="{a}?v={ver}"', html)
    if html != before:
        idx.write_text(html, encoding="utf-8")
    print(f"  stamped assets ?v={ver}")


if __name__ == "__main__":
    sys.exit(main())
